package transaction

type DataTransactionInput struct {
	ShippingDate string `json:"shipping_date"`
	Quantity float64 `json:"quantity"`
	ShipName string `json:"ship_name"`
	BargeName string `json:"barge_name"`
	VesselName string `json:"vessel_name"`
	CustomerName string `json:"customer_name"`
	LoadingPortName string `json:"loading_port_name"`
	LoadingPortLocation string `json:"loading_port_location"`
	UnloadingPortName string `json:"unloading_port_name"`
	UnloadingPortLocation string `json:"unloading_port_location"`
	DmoDestinationPort string `json:"dmo_destination_port"`
	SkbDate string `json:"skb_date"`
	SkbNumber string `json:"skb_number"`
	SkabDate string `json:"skab_date"`
	SkabNumber string `json:"skab_number"`
	BillOfLadingDate string `json:"bill_of_lading_date"`
	BillOfLadingNumber string `json:"bill_of_lading_number"`
	RoyaltyRate float64 `json:"royalty_rate"`
	DpRoyaltyCurrency string `json:"dp_royalty_currency"`
	DpRoyaltyPrice float64 `json:"dp_royalty_price"`
	DpRoyaltyDate string `json:"dp_royalty_date"`
	DpRoyaltyNtpn string `json:"dp_royalty_ntpn"`
	DpRoyaltyBillingCode string `json:"dp_royalty_billing_code"`
	DpRoyaltyTotal float64 `json:"dp_royalty_total"`
	PaymentDpRoyaltyCurrency string `json:"payment_dp_royalty_currency"`
	PaymentDpRoyaltyPrice float64 `json:"payment_dp_royalty_price"`
	PaymentDpRoyaltyDate string `json:"payment_dp_royalty_date"`
	PaymentDpRoyaltyNtpn string `json:"payment_dp_royalty_ntpn"`
	PaymentDpRoyaltyBillingCode string `json:"payment_dp_royalty_billing_code"`
	PaymentDpRoyaltyTotal float64 `json:"payment_dp_royalty_total"`
	LhvDate string `json:"lhv_date"`
	LhvNumber string `json:"lhv_number"`
	SurveyorName string `json:"surveyor_name"`
	CowDate string `json:"cow_date"`
	CowNumber string `json:"cow_number"`
	CoaDate string `json:"coa_date"`
	CoaNumber string `json:"coa_number"`
	QualityTmAr float64 `json:"quality_tm_ar"`
	QualityImAdb float64 `json:"quality_im_adb"`
	QualityAshAr float64 `json:"quality_ash_ar"`
	QualityAshAdb float64 `json:"quality_ash_adb"`
	QualityVmAdb float64 `json:"quality_vm_adb"`
	QualityFcAdb float64 `json:"quality_fc_adb"`
	QualityTsAr float64 `json:"quality_ts_ar"`
	QualityTsAdb float64 `json:"quality_ts_adb"`
	QualityCaloriesAr float64 `json:"quality_calories_ar"`
	QualityCaloriesAdb float64 `json:"quality_calories_adb"`
	BargingDistance float64 `json:"barging_distance"`
	SalesSystem string `json:"sales_system"`
	InvoiceDate string `json:"invoice_date"`
	InvoiceNumber string `json:"invoice_number"`
	InvoicePriceUnit float64 `json:"invoice_price_unit"`
	InvoicePriceTotal float64 `json:"invoice_price_total"`
	DmoReconciliationLetter string `json:"dmo_reconciliation_letter"`
	ContractDate string `json:"contract_date"`
	ContractNumber string `json:"contract_number"`
	DmoBuyerName string `json:"dmo_buyer_name"`
	DmoIndustryType string `json:"dmo_industry_type"`
	DmoStatusReconciliationLetter string `json:"dmo_status_reconciliation_letter"`
}
