package seeding

import (
	"ajebackend/model/master/country"
	"fmt"

	"gorm.io/gorm"
)

func SeedingCountry(db *gorm.DB) {

	tx := db.Begin()
	var checkCountry []country.Country

	tx.Find(&checkCountry)

	if len(checkCountry) > 0 {
		return
	}

	var createCountry []country.Country

	createCountry = append(createCountry,
		country.Country{Name: "Finlandia", Code: "FI"},
		country.Country{Name: "Bosnia And Herzegovina", Code: "BA"},
		country.Country{Name: "Aruba", Code: "AW"},
		country.Country{Name: "France", Code: "FR"},
		country.Country{Name: "Iraq", Code: "IQ"},
		country.Country{Name: "Argentina", Code: "AR"},
		country.Country{Name: "Malaysia", Code: "MY"},
		country.Country{Name: "Singapore", Code: "SG"},
		country.Country{Name: "Thailand", Code: "TH"},
		country.Country{Name: "China", Code: "CN"},
		country.Country{Name: "Kenya", Code: "KE"},
		country.Country{Name: "Uganda", Code: "UG"},
		country.Country{Name: "Austria", Code: "AT"},
		country.Country{Name: "United States", Code: "US"},
		country.Country{Name: "Antartica", Code: "AQ"},
		country.Country{Name: "Bangladesh", Code: "BD"},
		country.Country{Name: "Bulgaria", Code: "BG"},
		country.Country{Name: "Congo", Code: "CG"},
		country.Country{Name: "United Kingdom", Code: "GB"},
		country.Country{Name: "India", Code: "IN"},
		country.Country{Name: "Mexico", Code: "MX"},
		country.Country{Name: "Niger", Code: "NE"},
		country.Country{Name: "Norway", Code: "NO"},
		country.Country{Name: "Nepal", Code: "NP"},
		country.Country{Name: "Venezuela", Code: "VE"},
		country.Country{Name: "Vanuatu", Code: "VU"},
		country.Country{Name: "South Africa", Code: "ZA"},
		country.Country{Name: "Zimbabwe", Code: "ZW"},
		country.Country{Name: "United Arab Emirates", Code: "AE"},
		country.Country{Name: "Malawi", Code: "MW"},
		country.Country{Name: "Namibia", Code: "NA"},
		country.Country{Name: "New Caledonia", Code: "NC"},
		country.Country{Name: "Norfolk Island", Code: "NF"},
		country.Country{Name: "Nicaragua", Code: "NI"},
		country.Country{Name: "Nauru", Code: "NR"},
		country.Country{Name: "French Polynesia", Code: "PF"},
		country.Country{Name: "Antigua And Barbuda", Code: "AG"},
		country.Country{Name: "Anguilla", Code: "AI"},
		country.Country{Name: "Romania", Code: "RO"},
		country.Country{Name: "Serbia", Code: "RS"},
		country.Country{Name: "Solomon Islands", Code: "SB"},
		country.Country{Name: "Seychelles", Code: "SC"},
		country.Country{Name: "Saint Helena", Code: "SH"},
		country.Country{Name: "Svalbard And Jan Mayen", Code: "SJ"},
		country.Country{Name: "Sierra Leone", Code: "SL"},
		country.Country{Name: "San Marino", Code: "SM"},
		country.Country{Name: "El Salvador", Code: "SV"},
		country.Country{Name: "Swaziland", Code: "SZ"},
		country.Country{Name: "Turks And Caicos Islands", Code: "TC"},
		country.Country{Name: "Chad", Code: "TD"},
		country.Country{Name: "French Southern Territories", Code: "TF"},
		country.Country{Name: "Togo", Code: "TG"},
		country.Country{Name: "Tokelau", Code: "TK"},
		country.Country{Name: "Trinidad And Tobago", Code: "TT"},
		country.Country{Name: "Tuvalu", Code: "TV"},
		country.Country{Name: "Tanzania", Code: "TZ"},
		country.Country{Name: "Saint Vincent And The Grenadines", Code: "VC"},
		country.Country{Name: "Wallis And Futuna", Code: "WF"},
		country.Country{Name: "Mayotte", Code: "YT"},
		country.Country{Name: "Yugoslavia", Code: "YU"},
		country.Country{Name: "Virgin Islands, U.S", Code: "VI"},
		country.Country{Name: "Laos", Code: "LA"},
		country.Country{Name: "Netherlands  Antilles", Code: "AN"},
		country.Country{Name: "Azerbaijan", Code: "AZ"},
		country.Country{Name: "Timor Leste", Code: "TP"},
		country.Country{Name: "North Korea", Code: "KP"},
		country.Country{Name: "South Korea", Code: "KR"},
		country.Country{Name: "Zambia", Code: "ZM"},
		country.Country{Name: "Andorra", Code: "AD"},
		country.Country{Name: "Albania", Code: "AL"},
		country.Country{Name: "Angola", Code: "AO"},
		country.Country{Name: "Maldives", Code: "MV"},
		country.Country{Name: "Nigeria", Code: "NG"},
		country.Country{Name: "Papua New Guinea", Code: "PG"},
		country.Country{Name: "Palestinian Territory", Code: "PS"},
		country.Country{Name: "Senegal", Code: "SN"},
		country.Country{Name: "Ukraine", Code: "UA"},
		country.Country{Name: "Yemen", Code: "YE"},
		country.Country{Name: "Burundi", Code: "BI"},
		country.Country{Name: "Bouvet Island", Code: "BV"},
		country.Country{Name: "Central African Republic", Code: "CF"},
		country.Country{Name: "Colombia", Code: "CO"},
		country.Country{Name: "Czech Republic", Code: "CZ"},
		country.Country{Name: "Estonia", Code: "EE"},
		country.Country{Name: "Falkland Islands (Malvinas)", Code: "FK"},
		country.Country{Name: "Panama", Code: "PA"},
		country.Country{Name: "Reunion", Code: "RE"},
		country.Country{Name: "Slovenia", Code: "SI"},
		country.Country{Name: "Sao Tome And Principe", Code: "ST"},
		country.Country{Name: "Tonga", Code: "TO"},
		country.Country{Name: "United States Minor Outlying Islands", Code: "UM"},
		country.Country{Name: "Burkina Faso", Code: "BF"},
		country.Country{Name: "Barbados", Code: "BB"},
		country.Country{Name: "Bahrain", Code: "BH"},
		country.Country{Name: "Bolivia", Code: "BO"},
		country.Country{Name: "Brazil", Code: "BR"},
		country.Country{Name: "Canada", Code: "CA"},
		country.Country{Name: "Portugal", Code: "PT"},
		country.Country{Name: "Chile", Code: "CL"},
		country.Country{Name: "Denmark", Code: "DK"},
		country.Country{Name: "Western Sahara", Code: "EH"},
		country.Country{Name: "Spain", Code: "ES"},
		country.Country{Name: "Hong Kong", Code: "HK"},
		country.Country{Name: "Ireland", Code: "IE"},
		country.Country{Name: "Israel", Code: "IL"},
		country.Country{Name: "Iran", Code: "IR"},
		country.Country{Name: "Iceland", Code: "IS"},
		country.Country{Name: "Belgia", Code: "BE"},
		country.Country{Name: "Vietnam", Code: "VN"},
		country.Country{Name: "Virgin Islands, British", Code: "VG"},
		country.Country{Name: "Netherlands", Code: "NL"},
		country.Country{Name: "Italy", Code: "IT"},
		country.Country{Name: "New Zealand", Code: "NZ"},
		country.Country{Name: "Oman", Code: "OM"},
		country.Country{Name: "Peru", Code: "PE"},
		country.Country{Name: "Pakistan", Code: "PK"},
		country.Country{Name: "Poland", Code: "PL"},
		country.Country{Name: "Afghanistan", Code: "AF"},
		country.Country{Name: "Paraguay", Code: "PY"},
		country.Country{Name: "Palau", Code: "PW"},
		country.Country{Name: "Qatar", Code: "QA"},
		country.Country{Name: "Russian Federation", Code: "RU"},
		country.Country{Name: "Rwanda", Code: "RW"},
		country.Country{Name: "Saudi Arabia", Code: "SA"},
		country.Country{Name: "Sudan", Code: "SD"},
		country.Country{Name: "Sweden", Code: "SE"},
		country.Country{Name: "Slovakia", Code: "SK"},
		country.Country{Name: "Somalia", Code: "SO"},
		country.Country{Name: "Suriname", Code: "SR"},
		country.Country{Name: "Syrian Arab Republic", Code: "SY"},
		country.Country{Name: "Tajikistan", Code: "TJ"},
		country.Country{Name: "Turkmenistan", Code: "TM"},
		country.Country{Name: "Tunisia", Code: "TN"},
		country.Country{Name: "Turkey", Code: "TR"},
		country.Country{Name: "Taiwan", Code: "TW"},
		country.Country{Name: "Uruguay", Code: "UY"},
		country.Country{Name: "Uzbekistan", Code: "UZ"},
		country.Country{Name: "Holy See (Vatican City State)", Code: "VA"},
		country.Country{Name: "Niue", Code: "NU"},
		country.Country{Name: "Jamaica", Code: "JM"},
		country.Country{Name: "Kyrgyzstan", Code: "KG"},
		country.Country{Name: "Kuwait", Code: "KW"},
		country.Country{Name: "Kazakstan", Code: "KZ"},
		country.Country{Name: "Lebanon", Code: "LB"},
		country.Country{Name: "Sri Lanka", Code: "LK"},
		country.Country{Name: "Luxembourg", Code: "LU"},
		country.Country{Name: "Latvia", Code: "LV"},
		country.Country{Name: "Madagascar", Code: "MG"},
		country.Country{Name: "Myanmar", Code: "MM"},
		country.Country{Name: "Mongolia", Code: "MN"},
		country.Country{Name: "Macau", Code: "MO"},
		country.Country{Name: "Benin", Code: "BJ"},
		country.Country{Name: "Bermuda", Code: "BM"},
		country.Country{Name: "Bahamas", Code: "BS"},
		country.Country{Name: "Bhutan", Code: "BT"},
		country.Country{Name: "Botswana", Code: "BW"},
		country.Country{Name: "Belarus", Code: "BY"},
		country.Country{Name: "Belize", Code: "BZ"},
		country.Country{Name: "Cocos (Keeling) Islands", Code: "CC"},
		country.Country{Name: "Congo", Code: "CD"},
		country.Country{Name: "Switzerland", Code: "CH"},
		country.Country{Name: "Saint Pierre And Miquelon", Code: "PM"},
		country.Country{Name: "Pitcairn", Code: "PN"},
		country.Country{Name: "Puerto Rico", Code: "PR"},
		country.Country{Name: "Cote D'Ivoire", Code: "CI"},
		country.Country{Name: "Cook Islands", Code: "CK"},
		country.Country{Name: "Cameroon", Code: "CM"},
		country.Country{Name: "Costa Rica", Code: "CR"},
		country.Country{Name: "Cuba", Code: "CU"},
		country.Country{Name: "Cape Verde", Code: "CV"},
		country.Country{Name: "Christmas Island", Code: "CX"},
		country.Country{Name: "Cyprus", Code: "CY"},
		country.Country{Name: "Djibouti", Code: "DJ"},
		country.Country{Name: "Dominica", Code: "DM"},
		country.Country{Name: "Dominican Republic", Code: "DO"},
		country.Country{Name: "Algeria", Code: "DZ"},
		country.Country{Name: "Ecuador", Code: "EC"},
		country.Country{Name: "Egypt", Code: "EG"},
		country.Country{Name: "Eritrea", Code: "ER"},
		country.Country{Name: "Ethiopia", Code: "ET"},
		country.Country{Name: "Heard Island And Mcdonald Islands", Code: "HM"},
		country.Country{Name: "Fiji", Code: "FJ"},
		country.Country{Name: "Micronesia", Code: "FM"},
		country.Country{Name: "Faroe Islands", Code: "FO"},
		country.Country{Name: "Grenada", Code: "GD"},
		country.Country{Name: "Georgia", Code: "GE"},
		country.Country{Name: "French Guiana", Code: "GF"},
		country.Country{Name: "Gibraltar", Code: "GI"},
		country.Country{Name: "Greenland", Code: "GL"},
		country.Country{Name: "Gambia", Code: "GM"},
		country.Country{Name: "Guinea", Code: "GN"},
		country.Country{Name: "Equatorial Guinea", Code: "GQ"},
		country.Country{Name: "South Georgia And The South Sandwich Isl", Code: "GS"},
		country.Country{Name: "Guatemala", Code: "GT"},
		country.Country{Name: "Guam", Code: "GU"},
		country.Country{Name: "Guyana", Code: "GY"},
		country.Country{Name: "Honduras", Code: "HN"},
		country.Country{Name: "Croatia", Code: "HR"},
		country.Country{Name: "Haiti", Code: "HT"},
		country.Country{Name: "Hungary", Code: "HU"},
		country.Country{Name: "British Indian Ocean Territory", Code: "IO"},
		country.Country{Name: "Jordan", Code: "JO"},
		country.Country{Name: "Kiribati", Code: "KI"},
		country.Country{Name: "Comoros", Code: "KM"},
		country.Country{Name: "Cayman Islands", Code: "KY"},
		country.Country{Name: "Saint Lucia", Code: "LC"},
		country.Country{Name: "Liechtenstein", Code: "LI"},
		country.Country{Name: "Liberia", Code: "LR"},
		country.Country{Name: "Lesotho", Code: "LS"},
		country.Country{Name: "Lithuania", Code: "LT"},
		country.Country{Name: "Morocco", Code: "MA"},
		country.Country{Name: "Monaco", Code: "MC"},
		country.Country{Name: "Moldova", Code: "MD"},
		country.Country{Name: "Marshall Islands", Code: "MH"},
		country.Country{Name: "Macedonia", Code: "MK"},
		country.Country{Name: "Mali", Code: "ML"},
		country.Country{Name: "Martinique", Code: "MQ"},
		country.Country{Name: "Mauritania", Code: "MR"},
		country.Country{Name: "Montserrat", Code: "MS"},
		country.Country{Name: "Malta", Code: "MT"},
		country.Country{Name: "Mauritius", Code: "MU"},
		country.Country{Name: "Philippines", Code: "PH"},
		country.Country{Name: "Brunei Darussalam", Code: "BN"},
		country.Country{Name: "Cambodia", Code: "KH"},
		country.Country{Name: "Japan", Code: "JP"},
		country.Country{Name: "Australia", Code: "AU"},
		country.Country{Name: "Gabon", Code: "GA"},
		country.Country{Name: "Yunani", Code: "GR"},
		country.Country{Name: "Eropa", Code: "EU"},
		country.Country{Name: "Armenia", Code: "AM"},
		country.Country{Name: "Montenegro", Code: "ME"},
		country.Country{Name: "Germany", Code: "DE"},
		country.Country{Name: "Ghana", Code: "GH"},
		country.Country{Name: "Guadeloupe", Code: "GP"},
		country.Country{Name: "Guinea-Bissau", Code: "GW"},
		country.Country{Name: "Indonesia", Code: "ID"},
		country.Country{Name: "Saint Kitts And Nevis", Code: "KN"},
		country.Country{Name: "Libyan Arab Jamahiriya", Code: "LY"},
		country.Country{Name: "Northern Mariana Islands", Code: "MP"},
		country.Country{Name: "Mozambique", Code: "MZ"},
	)

	err := tx.Create(&createCountry).Error

	if err != nil {
		fmt.Println(err, "country")
		tx.Rollback()
		fmt.Println("Failed Seeding Country")
		return
	}

	tx.Commit()
}
