package seeding

import (
	"ajebackend/model/master/currency"
	"fmt"

	"gorm.io/gorm"
)

func SeedingCurrency(db *gorm.DB) {

	tx := db.Begin()
	var checkCurrency []currency.Currency
	tx.Find(&checkCurrency)

	if len(checkCurrency) > 0 {
		return
	}

	var createCurrency []currency.Currency
	createCurrency = append(createCurrency,
		currency.Currency{Name: "Andorran Peseta", Code: "ADP"},
		currency.Currency{Name: "UAE  Dirham", Code: "AED"},
		currency.Currency{Name: "Afghani", Code: "AFA"},
		currency.Currency{Name: "Lek", Code: "ALL"},
		currency.Currency{Name: "Armenian Dram", Code: "AMD"},
		currency.Currency{Name: "Netherlands Antillian Guilder", Code: "ANG"},
		currency.Currency{Name: "New Kwanza", Code: "AON"},
		currency.Currency{Name: "Argentina Peso", Code: "ARS"},
		currency.Currency{Name: "Schilling", Code: "ATS"},
		currency.Currency{Name: "Australian Dollar", Code: "AUD"},
		currency.Currency{Name: "Aruban Guilder", Code: "AWG"},
		currency.Currency{Name: "Azerbaijanian Manat", Code: "AZM"},
		currency.Currency{Name: "Barbados Dollar", Code: "BBD"},
		currency.Currency{Name: "Taka", Code: "BDT"},
		currency.Currency{Name: "Belgian Franc", Code: "BEF"},
		currency.Currency{Name: "Lev", Code: "BGL"},
		currency.Currency{Name: "Bahraini Dinar", Code: "BHD"},
		currency.Currency{Name: "Burundi Franc", Code: "BIF"},
		currency.Currency{Name: "Bermudian Dollar", Code: "BMD"},
		currency.Currency{Name: "Brunei Dollar", Code: "BND"},
		currency.Currency{Name: "Boliaiano", Code: "BOB"},
		currency.Currency{Name: "Brazilian Real", Code: "BRL"},
		currency.Currency{Name: "Bahamian Dollar", Code: "BSD"},
		currency.Currency{Name: "Ngultrum", Code: "BTN"},
		currency.Currency{Name: "Pula", Code: "BWP"},
		currency.Currency{Name: "Belarussian Ruble", Code: "BYB"},
		currency.Currency{Name: "Belize Dollar", Code: "BZD"},
		currency.Currency{Name: "Canadian Dollar", Code: "CAD"},
		currency.Currency{Name: "Swiss Franc", Code: "CHF"},
		currency.Currency{Name: "Chilean Peso", Code: "CLP"},
		currency.Currency{Name: "Yuan Renminbi", Code: "CNY"},
		currency.Currency{Name: "Colombian Peso", Code: "COP"},
		currency.Currency{Name: "Costa Rican Colon", Code: "CRC"},
		currency.Currency{Name: "Cuban Peso", Code: "CUP"},
		currency.Currency{Name: "Cape Verde Escudo", Code: "CVE"},
		currency.Currency{Name: "Cyprus Pound", Code: "CYP"},
		currency.Currency{Name: "Czech Koruna", Code: "CZK"},
		currency.Currency{Name: "Deustche Mark", Code: "DEM"},
		currency.Currency{Name: "Djibouti Franc", Code: "DJF"},
		currency.Currency{Name: "Danish Krone", Code: "DKK"},
		currency.Currency{Name: "Domincan Peso", Code: "DOP"},
		currency.Currency{Name: "Algerian Dinar", Code: "DZD"},
		currency.Currency{Name: "Sucre", Code: "ECS"},
		currency.Currency{Name: "Kroon", Code: "EEK"},
		currency.Currency{Name: "Egyptian Pound", Code: "EGP"},
		currency.Currency{Name: "Spainish peseta", Code: "ESP"},
		currency.Currency{Name: "Ethiopian Birr", Code: "ETB"},
		currency.Currency{Name: "Euro", Code: "EUR"},
		currency.Currency{Name: "Markka", Code: "FIM"},
		currency.Currency{Name: "Fiji Dollar", Code: "FJD"},
		currency.Currency{Name: "Falkland Islands Pound", Code: "FKP"},
		currency.Currency{Name: "Franch Franc", Code: "FRF"},
		currency.Currency{Name: "Pound Sterling", Code: "GBP"},
		currency.Currency{Name: "Georgian Coupon", Code: "GEK"},
		currency.Currency{Name: "Cedi", Code: "GHC"},
		currency.Currency{Name: "Gibraltar Pound", Code: "GIP"},
		currency.Currency{Name: "Dalasi", Code: "GMD"},
		currency.Currency{Name: "Guinea Franc", Code: "GNF"},
		currency.Currency{Name: "Drachma", Code: "GRD"},
		currency.Currency{Name: "Quetzal", Code: "GTQ"},
		currency.Currency{Name: "Guinea-Bissau Peso", Code: "GWP"},
		currency.Currency{Name: "Guyana Dollar", Code: "GYD"},
		currency.Currency{Name: "Hong Kong Dollar", Code: "HKD"},
		currency.Currency{Name: "Lempira", Code: "HNL"},
		currency.Currency{Name: "Croatian Dinar", Code: "HRD"},
		currency.Currency{Name: "Kuna", Code: "HRK"},
		currency.Currency{Name: "Gourde", Code: "HTG"},
		currency.Currency{Name: "Forint", Code: "HUF"},
		currency.Currency{Name: "Rupiah", Code: "IDR"},
		currency.Currency{Name: "Irish Pound", Code: "IEP"},
		currency.Currency{Name: "Shekel", Code: "ILS"},
		currency.Currency{Name: "Indian Rupee", Code: "INR"},
		currency.Currency{Name: "Iraqi Dinar", Code: "IQD"},
		currency.Currency{Name: "Iranian Rial", Code: "IRR"},
		currency.Currency{Name: "Iceland Krona", Code: "ISK"},
		currency.Currency{Name: "Italian Lira", Code: "ITL"},
		currency.Currency{Name: "Jamaican Dollar", Code: "JMD"},
		currency.Currency{Name: "Jordanian Dinar", Code: "JOD"},
		currency.Currency{Name: "Yen", Code: "JPY"},
		currency.Currency{Name: "Kenyan Shilling", Code: "KES"},
		currency.Currency{Name: "Som", Code: "KGS"},
		currency.Currency{Name: "Riel", Code: "KHR"},
		currency.Currency{Name: "Comoro Franc", Code: "KMF"},
		currency.Currency{Name: "North Korean Won", Code: "KPW"},
		currency.Currency{Name: "Won", Code: "KRW"},
		currency.Currency{Name: "Kuwauti Dinar", Code: "KWD"},
		currency.Currency{Name: "Cayman Islands Dollar", Code: "KYD"},
		currency.Currency{Name: "Tenge", Code: "KZT"},
		currency.Currency{Name: "Kip", Code: "LAK"},
		currency.Currency{Name: "Lebanese Pound", Code: "LBP"},
		currency.Currency{Name: "Sri Langka Rupee", Code: "LKR"},
		currency.Currency{Name: "Liberian Dollar", Code: "LRD"},
		currency.Currency{Name: "Loli", Code: "LSL"},
		currency.Currency{Name: "Lithuanian Litas", Code: "LTL"},
		currency.Currency{Name: "Luxembourg Franc", Code: "LUF"},
		currency.Currency{Name: "Latvian Lats#", Code: "LVL"},
		currency.Currency{Name: "Latvian Ruble", Code: "LVR"},
		currency.Currency{Name: "Libyan Dinar", Code: "LYD"},
		currency.Currency{Name: "Moroccoan Dirham", Code: "MAD"},
		currency.Currency{Name: "Moldovan Leu", Code: "MDL"},
		currency.Currency{Name: "Malagasy Franc", Code: "MGF"},
		currency.Currency{Name: "Kyat", Code: "MMK"},
		currency.Currency{Name: "Tugrik", Code: "MNT"},
		currency.Currency{Name: "Pataca", Code: "MOP"},
		currency.Currency{Name: "Ouguiya", Code: "MRO"},
		currency.Currency{Name: "Mallese Lira", Code: "MTL"},
		currency.Currency{Name: "Mauritius Pupee", Code: "MUR"},
		currency.Currency{Name: "Rufiyaa", Code: "MVR"},
		currency.Currency{Name: "Malawian Kwacha", Code: "MWK"},
		currency.Currency{Name: "Mexican  Nuevo Peso", Code: "MXN"},
		currency.Currency{Name: "Malaysian Ringgit", Code: "MYR"},
		currency.Currency{Name: "Metical", Code: "MZM"},
		currency.Currency{Name: "Namibia Dollar", Code: "NAD"},
		currency.Currency{Name: "Naira", Code: "NGN"},
		currency.Currency{Name: "Cordoba Oro", Code: "NIO"},
		currency.Currency{Name: "Netherlands Guilder", Code: "NLG"},
		currency.Currency{Name: "Norwegian Krone", Code: "NOK"},
		currency.Currency{Name: "Nepalese Rupee", Code: "NPR"},
		currency.Currency{Name: "New Zealand Dollar", Code: "NZD"},
		currency.Currency{Name: "Rial Omani", Code: "OMR"},
		currency.Currency{Name: "Balboa/US  Dollar", Code: "PAB"},
		currency.Currency{Name: "Nuevo Sol", Code: "PEN"},
		currency.Currency{Name: "Kina", Code: "PGK"},
		currency.Currency{Name: "Philippines Peso", Code: "PHP"},
		currency.Currency{Name: "Pakistan Rupee", Code: "PKR"},
		currency.Currency{Name: "Zloty", Code: "PLZ"},
		currency.Currency{Name: "Portuguese Escudo", Code: "PTE"},
		currency.Currency{Name: "Guarani", Code: "PYG"},
		currency.Currency{Name: "Qatari Rial", Code: "QAR"},
		currency.Currency{Name: "Leu", Code: "ROL"},
		currency.Currency{Name: "Russian Ruble", Code: "RUR"},
		currency.Currency{Name: "Rwanda Franc", Code: "RWF"},
		currency.Currency{Name: "Saudi Riyal", Code: "SAR"},
		currency.Currency{Name: "Solomon Islands Dollar", Code: "SBD"},
		currency.Currency{Name: "Seychelles Rupee", Code: "SCR"},
		currency.Currency{Name: "Sudanase Dinar", Code: "SDD"},
		currency.Currency{Name: "Sudanese Pound", Code: "SDP"},
		currency.Currency{Name: "Swedish Krone", Code: "SEK"},
		currency.Currency{Name: "Singapore Dollar", Code: "SGD"},
		currency.Currency{Name: "St. Helena Pound", Code: "SHP"},
		currency.Currency{Name: "Tolar", Code: "SIT"},
		currency.Currency{Name: "Slovak Koruna", Code: "SKK"},
		currency.Currency{Name: "Leone", Code: "SLL"},
		currency.Currency{Name: "Somalia shilling", Code: "SOS"},
		currency.Currency{Name: "Surinam Guilder", Code: "SRG"},
		currency.Currency{Name: "Dobra", Code: "STD"},
		currency.Currency{Name: "El Salvador Colon", Code: "SVC"},
		currency.Currency{Name: "Syrian Pound", Code: "SYP"},
		currency.Currency{Name: "Lilangeni", Code: "SZL"},
		currency.Currency{Name: "Baht", Code: "THB"},
		currency.Currency{Name: "Manat", Code: "TMM"},
		currency.Currency{Name: "Tunisian Dinar", Code: "TND"},
		currency.Currency{Name: "Pa'anga", Code: "TOP"},
		currency.Currency{Name: "Turkish Lira", Code: "TRL"},
		currency.Currency{Name: "Trinidad & Tobago Dollar", Code: "TTD"},
		currency.Currency{Name: "New Taiwan Dollar", Code: "TWD"},
		currency.Currency{Name: "Tanzania Shilling", Code: "TZS"},
		currency.Currency{Name: "Karbovanet", Code: "UAK"},
		currency.Currency{Name: "Uganda Shilling", Code: "UGX"},
		currency.Currency{Name: "US Dollar", Code: "USD"},
		currency.Currency{Name: "Peso Uruguayo", Code: "UYU"},
		currency.Currency{Name: "Ubekistan Sum", Code: "UZS"},
		currency.Currency{Name: "Bolivar", Code: "VEB"},
		currency.Currency{Name: "Dong", Code: "VND"},
		currency.Currency{Name: "Vatu", Code: "VUV"},
		currency.Currency{Name: "Tala", Code: "WST"},
		currency.Currency{Name: "CFA  Franc BAEC", Code: "XAF"},
		currency.Currency{Name: "East Caribbean Dollar", Code: "XCD"},
		currency.Currency{Name: "CFA Franc BCEAO", Code: "XOF"},
		currency.Currency{Name: "CFA Franc BEAC", Code: "XPF"},
		currency.Currency{Name: "Yemeni Rial", Code: "YER"},
		currency.Currency{Name: "New Yugosslavian", Code: "YUN"},
		currency.Currency{Name: "Financial Rand", Code: "ZAL"},
		currency.Currency{Name: "Rand", Code: "ZAR"},
		currency.Currency{Name: "Zambian Kwacha", Code: "ZMK"},
		currency.Currency{Name: "Zaife", Code: "ZRN"},
		currency.Currency{Name: "Zimbabwe Dollar", Code: "ZWD"},
	)

	err := tx.Create(&createCurrency).Error

	if err != nil {
		fmt.Println(err, "c")
		tx.Rollback()
		fmt.Println("Failed Seeding Currency")
		return
	}

	tx.Commit()
}
