package seeding

import (
	"ajebackend/model/master/pabeanoffice"
	"fmt"

	"gorm.io/gorm"
)

func SeedingPabeanOffice(db *gorm.DB) {

	tx := db.Begin()
	var checkPabeanOffice []pabeanoffice.PabeanOffice
	tx.Find(&checkPabeanOffice)

	if len(checkPabeanOffice) > 0 {
		return
	}

	var createPabeanOffice []pabeanoffice.PabeanOffice
	createPabeanOffice = append(createPabeanOffice,
		pabeanoffice.PabeanOffice{Name: "KPU TANJUNG PRIOK", Code: "040300"},
		pabeanoffice.PabeanOffice{Name: "KPU BATAM", Code: "020400"},
		pabeanoffice.PabeanOffice{Name: "KPU SOEKARNO-HATTA", Code: "050100"},
		pabeanoffice.PabeanOffice{Name: "KANWIL DJBC ACEH", Code: "130000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C SABANG", Code: "130300"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C BANDA ACEH", Code: "130100"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C MEULABOH", Code: "130400"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C LHOKSEUMAWE", Code: "130500"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C KUALA LANGSA", Code: "130600"},
		pabeanoffice.PabeanOffice{Name: "KANWIL DJBC SUMATERA UTARA", Code: "010000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP BELAWAN", Code: "010700"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP B MEDAN", Code: "010800"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C PEMATANGSIANTAR", Code: "011000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C SIBOLGA", Code: "011300"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C TELUK NIBUNG", Code: "011100"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C KUALA TANJUNG", Code: "011200"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP B KUALANAMU", Code: "010100"},
		pabeanoffice.PabeanOffice{Name: "BPIB BC TIPE B MEDAN", Code: "011600"},
		pabeanoffice.PabeanOffice{Name: "KANWIL DJBC RIAU", Code: "140000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP B PEKANBARU", Code: "021200"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP B DUMAI", Code: "020900"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C TEMBILAHAN", Code: "021500"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C BENGKALIS", Code: "021100"},
		pabeanoffice.PabeanOffice{Name: "PANGSAROP BC TIPE B BATAM", Code: "021800"},
		pabeanoffice.PabeanOffice{Name: "KANWIL DJBC KHUSUS KEPULAUAN RIAU", Code: "020000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP B TANJUNG BALAI KARIMUN", Code: "020100"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP B TANJUNGPINANG", Code: "020500"},
		pabeanoffice.PabeanOffice{Name: "PANGSAROP BC TIPE A TANJUNG BALAI KARIMUN", Code: "021900"},
		pabeanoffice.PabeanOffice{Name: "KANWIL DJBC SUMATERA BAGIAN TIMUR", Code: "030000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP B PALEMBANG", Code: "030100"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP B JAMBI", Code: "030600"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C PANGKALPINANG", Code: "030300"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C TANJUNGPANDAN", Code: "030500"},
		pabeanoffice.PabeanOffice{Name: "KANWIL DJBC SUMATERA BAGIAN BARAT", Code: "170000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP B TELUK BAYUR", Code: "011500"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C BENGKULU", Code: "030200"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP B BANDAR LAMPUNG", Code: "030700"},
		pabeanoffice.PabeanOffice{Name: "KANWIL DJBC BANTEN", Code: "150000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP MERAK", Code: "050400"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP A TANGERANG", Code: "150300"},
		pabeanoffice.PabeanOffice{Name: "KANWIL DJBC JAKARTA", Code: "040000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP A JAKARTA", Code: "040400"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP A MARUNDA", Code: "160200"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C KANTOR POS PASAR BARU", Code: "040600"},
		pabeanoffice.PabeanOffice{Name: "BPIB BC TIPE A JAKARTA", Code: "040500"},
		pabeanoffice.PabeanOffice{Name: "PANGSAROP BC TIPE B TANJUNG PRIOK", Code: "040700"},
		pabeanoffice.PabeanOffice{Name: "KANWIL DJBC JAWA BARAT", Code: "050000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP A BEKASI", Code: "050900"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TPM A BOGOR", Code: "050300"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP A PURWAKARTA", Code: "050800"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP A BANDUNG", Code: "050500"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C CIREBON", Code: "050700"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C TASIKMALAYA", Code: "050600"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP CIKARANG", Code: "051000"},
		pabeanoffice.PabeanOffice{Name: "KANWIL DJBC JAWA TENGAH DAN D.I. YOGYAKARTA", Code: "060000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP TANJUNG EMAS", Code: "060100"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMC KUDUS", Code: "060300"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP B SURAKARTA", Code: "060600"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C CILACAP", Code: "060400"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C PURWOKERTO", Code: "062000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C TEGAL", Code: "061000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP A SEMARANG", Code: "060800"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP B YOGYAKARTA", Code: "060700"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C MAGELANG", Code: "061100"},
		pabeanoffice.PabeanOffice{Name: "KANWIL DJBC JAWA TIMUR I", Code: "070000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP TANJUNG PERAK", Code: "070100"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP A PASURUAN", Code: "071300"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP JUANDA", Code: "070500"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP B GRESIK", Code: "070300"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C MADURA", Code: "070200"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C BOJONEGORO", Code: "070400"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP B SIDOARJO", Code: "071500"},
		pabeanoffice.PabeanOffice{Name: "BPIB BC TIPE B SURABAYA", Code: "071400"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMC MALANG", Code: "070600"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMC KEDIRI", Code: "070800"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C BLITAR", Code: "070700"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C MADIUN", Code: "071000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C JEMBER", Code: "071100"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C BANYUWANGI", Code: "160700"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C PROBOLINGGO", Code: "071200"},
		pabeanoffice.PabeanOffice{Name: "KANWIL DJBC BALI, NTB DAN NTT", Code: "080000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP NGURAH RAI", Code: "080100"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP A DENPASAR", Code: "080200"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C MATARAM", Code: "080300"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C SUMBAWA", Code: "080400"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C KUPANG", Code: "080500"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP B ATAMBUA", Code: "081400"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C MAUMERE", Code: "080700"},
		pabeanoffice.PabeanOffice{Name: "KANWIL DJBC KALIMANTAN BAGIAN BARAT", Code: "090000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP B PONTIANAK", Code: "090100"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C ENTIKONG", Code: "090200"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C NANGA BADAU", Code: "091000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C SINTETE", Code: "090500"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C KETAPANG", Code: "090400"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C JAGOI BABANG", Code: "092000"},
		pabeanoffice.PabeanOffice{Name: "KANWIL DJBC KALIMANTAN BAGIAN SELATAN", Code: "180000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP B BANJARMASIN", Code: "100100"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C SAMPIT", Code: "090700"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C PANGKALAN BUN", Code: "090800"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C PULANG PISAU", Code: "090900"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C KOTABARU", Code: "100200"},
		pabeanoffice.PabeanOffice{Name: "KANWIL DJBC KALIMANTAN BAGIAN TIMUR", Code: "100000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP B BALIKPAPAN", Code: "100300"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP B SAMARINDA", Code: "100500"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C BONTANG", Code: "100600"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C SANGATTA", Code: "101000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP B TARAKAN", Code: "100800"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C NUNUKAN", Code: "100900"},
		pabeanoffice.PabeanOffice{Name: "KANWIL DJBC SULAWESI BAGIAN SELATAN", Code: "110000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP B MAKASSAR", Code: "110100"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C PAREPARE", Code: "110300"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C MALILI", Code: "110400"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C KENDARI", Code: "110600"},
		pabeanoffice.PabeanOffice{Name: "KANWIL DJBC SULAWESI BAGIAN UTARA", Code: "190000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C PANTOLOAN", Code: "110800"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C MOROWALI", Code: "110900"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C LUWUK", Code: "111000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C BITUNG", Code: "111100"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C MANADO", Code: "111200"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C GORONTALO", Code: "111300"},
		pabeanoffice.PabeanOffice{Name: "PANGSAROP BC TIPE B PANTOLOAN", Code: "111400"},
		pabeanoffice.PabeanOffice{Name: "KANWIL DJBC MALUKU", Code: "120000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C AMBON", Code: "120100"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C TUAL", Code: "121000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C TERNATE", Code: "120200"},
		pabeanoffice.PabeanOffice{Name: "KANWIL DJBC KHUSUS PAPUA", Code: "200000"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C SORONG", Code: "120300"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C MANOKWARI", Code: "120400"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C BABO", Code: "122300"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C JAYAPURA", Code: "120600"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C AMAMAPARE", Code: "120800"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C BIAK", Code: "120900"},
		pabeanoffice.PabeanOffice{Name: "KPPBC TMP C MERAUKE", Code: "120700"},
		pabeanoffice.PabeanOffice{Name: "PANGSAROP BC TIPE B SORONG", Code: "121100"},
		pabeanoffice.PabeanOffice{Name: "KANWIL DJBC JAWA TIMUR II", Code: "160000"},
		pabeanoffice.PabeanOffice{Name: "Undefined", Code: "999999"},
	)

	err := tx.Create(&createPabeanOffice).Error

	if err != nil {
		tx.Rollback()
		fmt.Println("Failed Seeding Pabean Office")
		return
	}

	tx.Commit()
}
